# RecurrentLayer { #water_tank.layers.RecurrentLayer.RecurrentLayer }

`layers.RecurrentLayer.RecurrentLayer(self, size, tau=10.0, transfer_function='tanh')`

Reservoir of recurrently connected neurons.

$$\tau \, \frac{d \mathbf{x}(t)}{dt} + \mathbf{x}(t) = W^\text{in} \times I(t) + W^\text{rec} \times \mathbf{r}(t) + W^\text{fb} \times \mathbf{z}(t)$$
    
$$\mathbf{r}(t) = f(\mathbf{x}(t))$$

## Parameters

| Name                | Type   | Description        | Default    |
|---------------------|--------|--------------------|------------|
| `size`              | int    | number of neurons. | _required_ |
| `tau`               | float  | time constant.     | `10.0`     |
| `transfer_function` | str    | transfer function. | `'tanh'`   |

## Methods

| Name | Description |
| --- | --- |
| [output](#water_tank.layers.RecurrentLayer.RecurrentLayer.output) |  |
| [reset](#water_tank.layers.RecurrentLayer.RecurrentLayer.reset) | Resets the vectors x and r to 0. |
| [step](#water_tank.layers.RecurrentLayer.RecurrentLayer.step) | Performs one update of the internal variables. |

### output { #water_tank.layers.RecurrentLayer.RecurrentLayer.output }

`layers.RecurrentLayer.RecurrentLayer.output(self)`

#### Returns

| Type   | Description             |
|--------|-------------------------|
| None   | a vector of activities. |

### reset { #water_tank.layers.RecurrentLayer.RecurrentLayer.reset }

`layers.RecurrentLayer.RecurrentLayer.reset(self)`

Resets the vectors x and r to 0.

### step { #water_tank.layers.RecurrentLayer.RecurrentLayer.step }

`layers.RecurrentLayer.RecurrentLayer.step(self)`

Performs one update of the internal variables.