# SparseProjection { #water_tank.SparseProjection }

`SparseProjection(self, pre, post, weights, bias=None, sparseness=0.1)`

Sparse weight matrix.  Created and returned by `connect()`.

## Parameters

| Name         | Type                                                                     | Description                                                                                                     | Default    |
|--------------|--------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|------------|
| `pre`        | Layer                                                                    | input layer.                                                                                                    | _required_ |
| `post`       | Layer                                                                    | output layer.                                                                                                   | _required_ |
| `weights`    | typing.Union\[float, water_tank.RandomDistributions.RandomDistribution\] | float or `RandomDistribution` to create the weight matrix.                                                      | _required_ |
| `bias`       | typing.Union\[float, water_tank.RandomDistributions.RandomDistribution\] | bias per post neuron. If `None` or `False`, no bias is used. Otherwise, can be a float or `RandomDistribution`. | `None`     |
| `sparseness` | float                                                                    | density of the weight matrix.                                                                                   | `0.1`      |

## Methods

| Name | Description |
| --- | --- |
| [input](#water_tank.SparseProjection.input) |  |
| [load](#water_tank.SparseProjection.load) | Loads a dictionary of learnable parameters. |
| [nb_connections](#water_tank.SparseProjection.nb_connections) |  |
| [save](#water_tank.SparseProjection.save) | Returns a dictionary of learnable parameters. |
| [step](#water_tank.SparseProjection.step) | Performs a weighted sum of inputs plus bias. |

### input { #water_tank.SparseProjection.input }

`SparseProjection.input(self, idx)`

#### Returns

| Type          | Description                                                 |
|---------------|-------------------------------------------------------------|
| numpy.ndarray | the vector of inputs received by the neuron of index `idx`. |

### load { #water_tank.SparseProjection.load }

`SparseProjection.load(self, data)`

Loads a dictionary of learnable parameters.

### nb_connections { #water_tank.SparseProjection.nb_connections }

`SparseProjection.nb_connections(self, idx)`

#### Returns

| Type   | Description                                                  |
|--------|--------------------------------------------------------------|
| int    | the number of weights received by the neuron of index `idx`. |

### save { #water_tank.SparseProjection.save }

`SparseProjection.save(self)`

Returns a dictionary of learnable parameters.

### step { #water_tank.SparseProjection.step }

`SparseProjection.step(self)`

Performs a weighted sum of inputs plus bias.