# StaticInput { #water_tank.layers.StaticInput.StaticInput }

`layers.StaticInput.StaticInput(self, size)`

Static placeholder for input vectors.

## Parameters

| Name   | Type   | Description         | Default    |
|--------|--------|---------------------|------------|
| `size` | int    | size of the vector. | _required_ |

## Methods

| Name | Description |
| --- | --- |
| [output](#water_tank.layers.StaticInput.StaticInput.output) |  |
| [set](#water_tank.layers.StaticInput.StaticInput.set) | Sets the value of the vector. The dimensions must match with `self.size`. |
| [step](#water_tank.layers.StaticInput.StaticInput.step) | Does nothing. |

### output { #water_tank.layers.StaticInput.StaticInput.output }

`layers.StaticInput.StaticInput.output()`

#### Returns

| Type       | Description             |
|------------|-------------------------|
| np.ndarray | a vector of activities. |

### set { #water_tank.layers.StaticInput.StaticInput.set }

`layers.StaticInput.StaticInput.set(value)`

Sets the value of the vector. The dimensions must match with `self.size`.

#### Parameters

| Name    | Type       | Description       | Default    |
|---------|------------|-------------------|------------|
| `value` | np.ndarray | new vector value. | _required_ |

### step { #water_tank.layers.StaticInput.StaticInput.step }

`layers.StaticInput.StaticInput.step()`

Does nothing.