# TimeSeriesInput { #water_tank.layers.TimeSeriesInput.TimeSeriesInput }

`layers.TimeSeriesInput.TimeSeriesInput(self, size, loop=True)`

Dynamic placeholder for series of input vectors.

## Parameters

| Name   | Type   | Description                                                | Default    |
|--------|--------|------------------------------------------------------------|------------|
| `size` | int    | size of the input vector.                                  | _required_ |
| `loop` | bool   | defines whether the buffer loops when arriving at the end. | `True`     |

## Methods

| Name | Description |
| --- | --- |
| [output](#water_tank.layers.TimeSeriesInput.TimeSeriesInput.output) |  |
| [reset](#water_tank.layers.TimeSeriesInput.TimeSeriesInput.reset) | Resets the buffer. |
| [set](#water_tank.layers.TimeSeriesInput.TimeSeriesInput.set) | Sets the buffer to `value`. |
| [step](#water_tank.layers.TimeSeriesInput.TimeSeriesInput.step) | Reads the next value. |

### output { #water_tank.layers.TimeSeriesInput.TimeSeriesInput.output }

`layers.TimeSeriesInput.TimeSeriesInput.output(self)`

#### Returns

| Type          | Description             |
|---------------|-------------------------|
| numpy.ndarray | a vector of activities. |

### reset { #water_tank.layers.TimeSeriesInput.TimeSeriesInput.reset }

`layers.TimeSeriesInput.TimeSeriesInput.reset(self)`

Resets the buffer.

### set { #water_tank.layers.TimeSeriesInput.TimeSeriesInput.set }

`layers.TimeSeriesInput.TimeSeriesInput.set(self, value)`

Sets the buffer to `value`.

### step { #water_tank.layers.TimeSeriesInput.TimeSeriesInput.step }

`layers.TimeSeriesInput.TimeSeriesInput.step(self)`

Reads the next value.